# Site Settings
title: 离开
email: youremail@xyz.com
description: Some text about your blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wolfleave.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
port: 4001

# User Settings
username: 离开
user_description: Some text about you.
disqus_username: wolfleave

# Social Media
# Remove the item if you don't need it
github_username: lxbwin@163.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
plugins:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# Content Template
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "李幸斌"
